### ISSUE TITLE
create release from only code branch

### ISSUE THREAD

**Issue by lpantano** [TJU-CMC-Org/MINTmap#2]
Hi Philipe,

thanks a lot for creating the branch. Do you think you can create a release from that branch? 

It would be easier and cleaner to implement in bioconda :)

thanks!

**Comment by phillipeloher** [comment]
Sure, please see https://github.com/TJU-CMC-Org/MINTmap/releases/tag/MINTmap_codesOnlyNotRunnable_v1.0 .  I also created another release with the necessary data tables for human.
